### ISSUE TITLE
GH Workflow automation for the Examples repository

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry-examples#27]
This https://github.com/Apicurio/apicurio-registry-examples repository contains a set of example applications for Apicurio Registry.  It's things like Kafka applications that show how to use our SerDes classes in practice.  This repository should be released/tagged every time the Apicurio Registry project is released.

It would be ideal if the release of this repository was triggered by a release of Registry, similar to what we're doing now for e.g. container images and CLI builds.  That way if it fails we can retry it.

**Also** I think we should trigger a build (not a release) of this repository every time `master` is updated in Apicurio Registry and every time `master` (or `main` or whatever) is updated in Apicurio Registry Examples.  The goal is to make sure that this repository is always building successfully against the latest Apicurio Registry.  So I guess we'll need a workflow that builds both?  If the examples build fails then we should send a notification to gchat.

**Comment by riprasad** [comment]
Necessary changes are done to the registry and examples workflows to accomodate the above request.

[changes in examples workflow](https://github.com/Apicurio/apicurio-registry-examples/commit/a10759d0f01ad042024a782116ecf7e8f97fece5)

[changes in registry workflow](https://github.com/Apicurio/apicurio-registry/pull/2296)
