### ISSUE TITLE
JsonSchemaValidationExample fails when used against Red Hat OpenShift Service Registry

### ISSUE THREAD

**Issue by mostmark** [Apicurio/apicurio-registry-examples#28]
When using the example io.apicurio.registry.examples.validation.json.JsonSchemaValidationExample agains Red Hat OpenShift Service Registry the example fails with the following error message:

`Exception in thread "main" io.apicurio.rest.client.auth.exception.NotAuthorizedException: Authentication exception`

This is because the RegistryClient is created without the required OIDC credentials. Similar to the JsonValidator the RegistryClient needs to be configured with OIDC credentials when running the example against a service registry instance that has security enabled.

Adding a helper method like the following could fix the problem.

```
    /**
     * Creates the registry client
     */
    private static RegistryClient createRegistryClient(String registryUrl) {
        final String tokenEndpoint = System.getenv(SchemaResolverConfig.AUTH_TOKEN_ENDPOINT);

        //Just if security values are present, then we configure them.
        if (tokenEndpoint != null) {
            final String authClient = System.getenv(SchemaResolverConfig.AUTH_CLIENT_ID);
            final String authSecret = System.getenv(SchemaResolverConfig.AUTH_CLIENT_SECRET);
            ApicurioHttpClient httpClient = ApicurioHttpClientFactory.create(tokenEndpoint, new AuthErrorHandler());
            OidcAuth auth = new OidcAuth(httpClient, authClient, authSecret);
            return RegistryClientFactory.create(registryUrl, Collections.emptyMap(), auth);
        } else {
            return RegistryClientFactory.create(registryUrl);
        }
    }
```

**Comment by EricWittmann** [comment]
I think this was fixed in https://github.com/Apicurio/apicurio-registry-examples/pull/29

Thanks for the contribution, @mostmark !
